version: '3'

services:
  github-fav-repos:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 500M  
    ports:
      - "3000:3000"
    depends_on:
      - reposerver

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - "4000:4000"
    depends_on:
      - reposerver

  reposerver:
    image: gcr.io/hiring-278615/reposerver:v1.1
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - "8080:8080"
