# Use Node.js as base image
FROM node:16

# Set working directory
WORKDIR /server

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy server files
COPY . .

# Transpile TypeScript to JavaScript
RUN npm run build-server

# Expose port 4000
EXPOSE 4000

# Run server.js from the dist folder
CMD ["node", "dist/server.js"]
